services:
  - type: web
    name: waze3li-backend
    runtime: node
    runtimeVersion: 18.17.0
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    plan: free
    rootDir: backend
