services:
  - type: web
    name: waze3li-backend
    env: docker
    buildCommand: docker build -t waze3li-backend .
    startCommand: docker run -p 5000:5000 waze3li-backend
    autoDeploy: true
    plan: free
    rootDir: backend
